
# SEO settings
title: "Leily"
title2: "s'Blog" # default: ""
description: "Leily 的博客."
keywords: "python linux saltstack bash 等"
url: http://leilyzhang.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/leilyzhang
disqus_shortname: "leily"
twitter_username: "leily"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Leily"
  job      : "SA"
  bio      : "1+1=3 is always TRUE in my world, SO，JUST it."
  thumb    : /images/author.jpg
  email    : 274154142@qq.com
  url      : http://leilyzhang.github.io
  github   : http://github.com/leilyzhang
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "leilyzhang"
twitter_site: "@leilyzhang"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
